[rospy.client][INFO] 2020-02-27 09:12:09,571: init_node, name[/sr_determine_rois_20344_1582774929526], pid[20344]
[xmlrpc][INFO] 2020-02-27 09:12:09,572: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-02-27 09:12:09,573: Started XML-RPC server [http://itachi-HP-Pavilion-Laptop-15-cc1xx:33575/]
[rospy.init][INFO] 2020-02-27 09:12:09,573: ROS Slave URI: [http://itachi-HP-Pavilion-Laptop-15-cc1xx:33575/]
[rospy.impl.masterslave][INFO] 2020-02-27 09:12:09,573: _ready: http://itachi-HP-Pavilion-Laptop-15-cc1xx:33575/
[xmlrpc][INFO] 2020-02-27 09:12:09,574: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-02-27 09:12:09,574: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2020-02-27 09:12:09,574: registering subscriber topic [/usb_cam/image_rect] type [sensor_msgs/Image] with master
[rospy.internal][INFO] 2020-02-27 09:12:09,576: topic[/usb_cam/image_rect] adding connection to [http://itachi-HP-Pavilion-Laptop-15-cc1xx:35047/], count 0
[rospy.init][INFO] 2020-02-27 09:12:09,673: registered with master
[rospy.rosout][INFO] 2020-02-27 09:12:09,674: initializing /rosout core topic
[rospy.rosout][INFO] 2020-02-27 09:12:09,676: connected to core topic /rosout
[rospy.simtime][INFO] 2020-02-27 09:12:09,677: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2020-02-27 09:12:09,790: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:09,811: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:09,815: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:09,821: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:09,829: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:09,837: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:09,848: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:09,865: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:09,879: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rospy.internal][INFO] 2020-02-27 09:12:09,881: topic[/rosout] adding connection to [/rosout], count 0
[rosout][ERROR] 2020-02-27 09:12:09,917: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:09,940: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:09,990: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,015: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,052: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,080: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,103: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,135: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,173: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,209: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,252: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,286: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,310: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,339: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,369: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,405: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,437: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,482: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,524: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,541: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,571: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,614: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,645: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,674: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,719: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,751: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,781: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,814: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,846: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,884: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,914: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,943: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:10,975: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,019: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,054: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,086: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,118: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,149: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,178: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,215: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,259: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,302: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,315: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,345: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,386: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,423: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,453: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,489: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,508: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,554: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,589: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,613: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,647: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,679: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,715: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,762: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,782: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,815: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,855: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,882: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,916: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,942: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:11,980: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:12,015: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:12,058: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:12,097: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

[rosout][ERROR] 2020-02-27 09:12:12,114: bad callback: <bound method sr_determine_rois.callback of <__main__.sr_determine_rois instance at 0x7f7fc56e0ab8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "blank_temp.py", line 70, in callback
    frame = cv2.imread(self.cv_image)
TypeError: expected string or Unicode object, numpy.ndarray found

